
[[carousel_slides]]
caption = "Register Now!"
description = "Join us for an exciting online workshop hosted by DIPY. Our comprehensive program is design to equip you with the skills and the knowledge needed to master the latest techniques and tools in structural and diffusion Imaging."
img = "dipy_workshop_2025.png"
link = "https://workshop.dipy.org"

[[carousel_slides]]
caption = "Patch2Self2, CVPR 2024"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/a45bc26dc8d2225ffca494d7f38f05c3cc8dbf1c/P2S2.png"
link = "https://openaccess.thecvf.com/content/CVPR2024/papers/Fadnavis_Patch2Self2_Self-supervised_Denoising_on_Coresets_via_Matrix_Sketching_CVPR_2024_paper.pdf"

[[carousel_slides]]
caption = "EVAC+, Communications Medicine 2024"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/dipy_main_evac.png"
link = "https://www.nature.com/articles/s43856-024-00452-8"

[[carousel_slides]]
caption = "PNAS 2023"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/pnas_2023.jpg"
link = "https://www.pnas.org/doi/abs/10.1073/pnas.2303491120"

[[carousel_slides]]
caption = "Patch2Self, NeurIPS 2020"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/patch2self_banner.PNG"

[[carousel_slides]]
caption = "BUAN, Scientific Reports 2020"
description = ""
img = "https://raw.githubusercontent.com/dipy/dipy_data/master/buan_profiles.png"

[[carousel_slides]]
caption = "SLR, NeuroImage 2015"
description = ""
img = "https://github.com/Garyfallidis/garyfallidis.github.com/blob/master_bak/images/slr_banner.jpg?raw=true"

[[carousel_slides]]
caption = "QuickBundles, Frontiers 2012"
description = ""
img = "https://github.com/Garyfallidis/garyfallidis.github.com/blob/master_bak/images/quickbundles_banner.jpg?raw=true"

[[explore_items]]
title = "Command-Line Interfaces"
icon = "cli.svg"
description = "All the algorithms are available using CLI. You can also create your own algorithms."
link = "https://docs.dipy.org/stable/interfaces/index"

[[explore_items]]
title = "Statistical Analysis"
icon = "stat.svg"
description = "DIPY allows you to use different methods like BUAN, AFQ, K-Fold cross validation."
link = "https://docs.dipy.org/stable/examples_built/index.html#streamlines-analysis-and-connectivity"

[[explore_items]]
title = "Reconstruction"
icon = "reconstruction.svg"
description = "<b>Single shell</b>: DTI, CSA, SFM, SDT, Q-Ball, CSD, and many more. <br/>  <b>Multi shell</b>: GQI, DTI, DKI, SHORE, MAPMRI, MSMT-CSD, and many more."
link = "https://docs.dipy.org/stable/examples_built/index.html#reconstruction"

[[explore_items]]
title = "Registration"
icon = "registration.svg"
description = "Affine Registration, Diffeomorphic 2D/3D Registration, Streamlines based Registration, and much more."
link = "https://docs.dipy.org/stable/examples_built/index.html#registration"

[[explore_items]]
title = "Tractography"
icon = "tractography.svg"
description = "Probabilistic Tracking, Deterministic Tracking, PFT Tracking, and much more."
link = "https://docs.dipy.org/stable/examples_built/index.html#fiber-tracking"

[[explore_items]]
title = "Denoising"
icon = "denoise.png"
description = "Patch2Self, Non Local Means, Gibbs Unringing, MP-PCA, L-PCA and much more."
link = "https://docs.dipy.org/stable/examples_built/preprocessing/denoise_patch2self.html#sphx-glr-examples-built-preprocessing-denoise-patch2self-py"

[[explore_items]]
title = "Visualization"
icon = "chart.png"
description = "ODFs visualization, interactive tractogram visualization, Advanced UI and Shaders, and much more."
link = "https://docs.dipy.org/stable/examples_built/index.html#visualization"

[[explore_items]]
title = "Pre-Processing"
icon = "preprocessing.png"
description = "Brain extraction, SNR estimation, Reslice Datasets, and much more."
link = "https://docs.dipy.org/stable/examples_built/index.html#preprocessing"

[[sponsors]]
name = "NIH NIBIB"
image = "NIH_NIBIB.png"
url = "https://www.nibib.nih.gov/"

[[sponsors]]
name = "Luddy IU"
image = "luddy.png"
url = "https://luddy.indiana.edu/"

[[sponsors]]
name = "Google Summer of Code"
image = "gsoc.png"
url = "https://summerofcode.withgoogle.com/"

[[sponsors]]
name = "Indiana University"
image = "iu.webp"
url = "https://www.iu.edu/"

[[sponsors]]
name = "UW eScience Institute"
image = "uwescience.png"
url = "https://escience.washington.edu/"

[[sponsors]]
name = "Chan Zuckerberg Initiative"
image = "czi_logo.png"
url = "https://chanzuckerberg.com/eoss/proposals/strengthening-computational-neuroanatomy-using-dipy/"
